//! Renders the compliance run's results as the Markdown/JSON pair the
//! task asks for, in the terse, tabular style of `ds-catalog-broker-rs`'s
//! own `compliance/*.md` reports.

use std::fmt::Write as _;

use engine::WireDecision;
use serde::Serialize;

pub enum CaseResult {
    Passed { slug: String, title: String, decision: WireDecision },
    Failed { slug: String, title: String, expected: WireDecision, actual: WireDecision, reason: String },
    Skipped { slug: String, title: String, reason: String },
}

fn decision_str(d: WireDecision) -> &'static str {
    match d {
        WireDecision::Allow => "Allow",
        WireDecision::Deny => "Deny",
        WireDecision::Error => "Error",
    }
}

#[derive(Serialize)]
struct JsonCase {
    slug: String,
    title: String,
    status: &'static str,
    decision: Option<&'static str>,
    expected: Option<&'static str>,
    actual: Option<&'static str>,
    reason: Option<String>,
}

#[derive(Serialize)]
struct JsonReport {
    total: usize,
    passed: usize,
    failed: usize,
    skipped: usize,
    failing_case_ids: Vec<String>,
    skipped_case_ids: Vec<String>,
    cases: Vec<JsonCase>,
}

pub fn render(results: &[CaseResult]) -> (String, String) {
    let passed = results.iter().filter(|r| matches!(r, CaseResult::Passed { .. })).count();
    let failed = results.iter().filter(|r| matches!(r, CaseResult::Failed { .. })).count();
    let skipped = results.iter().filter(|r| matches!(r, CaseResult::Skipped { .. })).count();
    let total = results.len();

    let mut md = String::new();
    let _ = writeln!(md, "# ODRL-Test-Suite compliance report");
    let _ = writeln!(md);
    let _ = writeln!(
        md,
        "Generated by `compliance-runner` against the vendored \
         [SolidLabResearch/ODRL-Test-Suite](https://github.com/SolidLabResearch/ODRL-Test-Suite) \
         (`compliance/vendor/odrl-test-suite`), adapted into `engine`'s Section 5.2 JSON contract \
         per the adapter's own translation convention (`compliance-runner/src/translate.rs`)."
    );
    let _ = writeln!(md);
    let _ = writeln!(md, "| total | passed | failed | skipped |");
    let _ = writeln!(md, "|---|---|---|---|");
    let _ = writeln!(md, "| {total} | {passed} | {failed} | {skipped} |");
    let _ = writeln!(md);
    let _ = writeln!(
        md,
        "Since `engine`'s `odrl:includedIn` action-coverage revision, `translate.rs` no \
         longer pre-filters a policy's rules by action at all — every rule survives translation \
         with its own declared action (or, absent one, the request's own — see that module's doc \
         comment), and `engine::decide` alone decides whether a rule's action covers the \
         request's. This once regressed two vendored fixtures (`testcase-014-alice-sell`, \
         `testcase-020-bob-sell`): each policy's *only* rule is a prohibition on `use` that does \
         not cover the fixture's `sell` request, leaving that policy's `permissions` list empty — \
         which `decide`'s own Section 4.3 departure treated as *open* regardless of an unrelated, \
         non-covering prohibition being present, producing Allow where this suite's closed-world \
         ground truth expects Deny. Earlier revisions never surfaced this: a translate-time action \
         pre-filter used to discard such a policy's sole rule outright, which happened to route the \
         request through Section 5.2's *different* empty-policies default (closed), masking the \
         divergence rather than resolving it. Both fixtures pass again as of the `Behaviour` \
         parameter (Section 4.3's empty-permissions departure is now a real, host-configurable \
         setting rather than an algorithmic constant; this runner sets it to `Closed`, matching this \
         suite's own closed-world assumption): see `README.md`'s compliance summary for the fuller \
         account. This was a property of the vendored engine's own decision algorithm, fixed by \
         giving hosts the choice it always claimed to be making, not a translation bug and not \
         silently worked around."
    );
    let _ = writeln!(md);

    let _ = writeln!(md, "## Failing cases");
    let _ = writeln!(md);
    if failed == 0 {
        let _ = writeln!(md, "None.");
    } else {
        let _ = writeln!(md, "| case | title | expected | actual | reason |");
        let _ = writeln!(md, "|---|---|---|---|---|");
        for r in results {
            if let CaseResult::Failed { slug, title, expected, actual, reason } = r {
                let _ = writeln!(
                    md,
                    "| {slug} | {title} | {} | {} | {} |",
                    decision_str(*expected),
                    decision_str(*actual),
                    reason.replace('|', "\\|")
                );
            }
        }
    }
    let _ = writeln!(md);

    let _ = writeln!(md, "## Skipped cases");
    let _ = writeln!(md);
    if skipped == 0 {
        let _ = writeln!(md, "None.");
    } else {
        let _ = writeln!(md, "| case | title | Section 7 citation |");
        let _ = writeln!(md, "|---|---|---|");
        for r in results {
            if let CaseResult::Skipped { slug, title, reason } = r {
                let _ = writeln!(md, "| {slug} | {title} | {} |", reason.replace('|', "\\|"));
            }
        }
    }
    let _ = writeln!(md);

    let _ = writeln!(md, "## Passing cases");
    let _ = writeln!(md);
    let _ = writeln!(md, "| case | title | decision |");
    let _ = writeln!(md, "|---|---|---|");
    for r in results {
        if let CaseResult::Passed { slug, title, decision } = r {
            let _ = writeln!(md, "| {slug} | {title} | {} |", decision_str(*decision));
        }
    }

    let cases = results
        .iter()
        .map(|r| match r {
            CaseResult::Passed { slug, title, decision } => JsonCase {
                slug: slug.clone(),
                title: title.clone(),
                status: "passed",
                decision: Some(decision_str(*decision)),
                expected: None,
                actual: None,
                reason: None,
            },
            CaseResult::Failed { slug, title, expected, actual, reason } => JsonCase {
                slug: slug.clone(),
                title: title.clone(),
                status: "failed",
                decision: None,
                expected: Some(decision_str(*expected)),
                actual: Some(decision_str(*actual)),
                reason: Some(reason.clone()),
            },
            CaseResult::Skipped { slug, title, reason } => JsonCase {
                slug: slug.clone(),
                title: title.clone(),
                status: "skipped",
                decision: None,
                expected: None,
                actual: None,
                reason: Some(reason.clone()),
            },
        })
        .collect();

    let json_report = JsonReport {
        total,
        passed,
        failed,
        skipped,
        failing_case_ids: results
            .iter()
            .filter_map(|r| match r {
                CaseResult::Failed { slug, .. } => Some(slug.clone()),
                _ => None,
            })
            .collect(),
        skipped_case_ids: results
            .iter()
            .filter_map(|r| match r {
                CaseResult::Skipped { slug, .. } => Some(slug.clone()),
                _ => None,
            })
            .collect(),
        cases,
    };

    let json = serde_json::to_string_pretty(&json_report).expect("JsonReport always serializes");
    (md, json)
}
