//! Renders the compliance run's results as the Markdown/JSON pair the
//! task asks for, in the terse, tabular style of `ds-catalog-broker-rs`'s
//! own `compliance/*.md` reports.

use std::fmt::Write as _;

use engine::WireDecision;
use serde::Serialize;

pub enum CaseResult {
    Passed { slug: String, title: String, decision: WireDecision },
    Failed { slug: String, title: String, expected: WireDecision, actual: WireDecision, reason: String },
    Skipped { slug: String, title: String, reason: String },
}

fn decision_str(d: WireDecision) -> &'static str {
    match d {
        WireDecision::Allow => "Allow",
        WireDecision::Deny => "Deny",
        WireDecision::Error => "Error",
    }
}

#[derive(Serialize)]
struct JsonCase {
    slug: String,
    title: String,
    status: &'static str,
    decision: Option<&'static str>,
    expected: Option<&'static str>,
    actual: Option<&'static str>,
    reason: Option<String>,
}

#[derive(Serialize)]
struct JsonReport {
    total: usize,
    passed: usize,
    failed: usize,
    skipped: usize,
    failing_case_ids: Vec<String>,
    skipped_case_ids: Vec<String>,
    cases: Vec<JsonCase>,
}

pub fn render(results: &[CaseResult]) -> (String, String) {
    let passed = results.iter().filter(|r| matches!(r, CaseResult::Passed { .. })).count();
    let failed = results.iter().filter(|r| matches!(r, CaseResult::Failed { .. })).count();
    let skipped = results.iter().filter(|r| matches!(r, CaseResult::Skipped { .. })).count();
    let total = results.len();

    let mut md = String::new();
    let _ = writeln!(md, "# ODRL-Test-Suite compliance report");
    let _ = writeln!(md);
    let _ = writeln!(
        md,
        "Generated by `compliance-runner` against the vendored \
         [SolidLabResearch/ODRL-Test-Suite](https://github.com/SolidLabResearch/ODRL-Test-Suite) \
         (`compliance/vendor/odrl-test-suite`), adapted into `engine`'s Section 5.2 JSON contract \
         per the adapter's own translation convention (`compliance-runner/src/translate.rs`)."
    );
    let _ = writeln!(md);
    let _ = writeln!(md, "| total | passed | failed | skipped |");
    let _ = writeln!(md, "|---|---|---|---|");
    let _ = writeln!(md, "| {total} | {passed} | {failed} | {skipped} |");
    let _ = writeln!(md);
    let _ = writeln!(
        md,
        "Every vendored fixture policy carries exactly one permission or prohibition rule, so \
         `translate.rs`'s \"omit the policy when its sole rule doesn't pertain to this request\" \
         convention (see that module's doc comment) is always all-or-nothing here: this corpus \
         never exercises `decide`'s own Section 4.3 open-on-empty-permissions departure as an \
         observable divergence from this suite's closed-world default. A corpus with a policy \
         mixing a matched permission and an unrelated prohibition could still surface that gap as \
         a genuine failure; this one happens not to."
    );
    let _ = writeln!(md);

    let _ = writeln!(md, "## Failing cases");
    let _ = writeln!(md);
    if failed == 0 {
        let _ = writeln!(md, "None.");
    } else {
        let _ = writeln!(md, "| case | title | expected | actual | reason |");
        let _ = writeln!(md, "|---|---|---|---|---|");
        for r in results {
            if let CaseResult::Failed { slug, title, expected, actual, reason } = r {
                let _ = writeln!(
                    md,
                    "| {slug} | {title} | {} | {} | {} |",
                    decision_str(*expected),
                    decision_str(*actual),
                    reason.replace('|', "\\|")
                );
            }
        }
    }
    let _ = writeln!(md);

    let _ = writeln!(md, "## Skipped cases");
    let _ = writeln!(md);
    if skipped == 0 {
        let _ = writeln!(md, "None.");
    } else {
        let _ = writeln!(md, "| case | title | Section 7 citation |");
        let _ = writeln!(md, "|---|---|---|");
        for r in results {
            if let CaseResult::Skipped { slug, title, reason } = r {
                let _ = writeln!(md, "| {slug} | {title} | {} |", reason.replace('|', "\\|"));
            }
        }
    }
    let _ = writeln!(md);

    let _ = writeln!(md, "## Passing cases");
    let _ = writeln!(md);
    let _ = writeln!(md, "| case | title | decision |");
    let _ = writeln!(md, "|---|---|---|");
    for r in results {
        if let CaseResult::Passed { slug, title, decision } = r {
            let _ = writeln!(md, "| {slug} | {title} | {} |", decision_str(*decision));
        }
    }

    let cases = results
        .iter()
        .map(|r| match r {
            CaseResult::Passed { slug, title, decision } => JsonCase {
                slug: slug.clone(),
                title: title.clone(),
                status: "passed",
                decision: Some(decision_str(*decision)),
                expected: None,
                actual: None,
                reason: None,
            },
            CaseResult::Failed { slug, title, expected, actual, reason } => JsonCase {
                slug: slug.clone(),
                title: title.clone(),
                status: "failed",
                decision: None,
                expected: Some(decision_str(*expected)),
                actual: Some(decision_str(*actual)),
                reason: Some(reason.clone()),
            },
            CaseResult::Skipped { slug, title, reason } => JsonCase {
                slug: slug.clone(),
                title: title.clone(),
                status: "skipped",
                decision: None,
                expected: None,
                actual: None,
                reason: Some(reason.clone()),
            },
        })
        .collect();

    let json_report = JsonReport {
        total,
        passed,
        failed,
        skipped,
        failing_case_ids: results
            .iter()
            .filter_map(|r| match r {
                CaseResult::Failed { slug, .. } => Some(slug.clone()),
                _ => None,
            })
            .collect(),
        skipped_case_ids: results
            .iter()
            .filter_map(|r| match r {
                CaseResult::Skipped { slug, .. } => Some(slug.clone()),
                _ => None,
            })
            .collect(),
        cases,
    };

    let json = serde_json::to_string_pretty(&json_report).expect("JsonReport always serializes");
    (md, json)
}
